### PR TITLE
Dependency: update toml to 0.7

### PR DESCRIPTION
**Pull request by WindSoilder**

### CODE REVIEW

**Comment by WindSoilder** [comment]
Hi, I found out that the dependency `toml` is not up to date, which may cause some applications (like nushell) to compile it multiple times. It would be nice if toml was updated and released without breaking semver compatibility in version numbers. Then our echo system will benefit from it too :) What do you think?

**Comment by BenjaminRi** [comment]
@WindSoilder Fyi: You will most likely not get a response here. @mxre has abandoned this repository and it no longer works with up to date Rust compilers. For more info, please refer to #40.

There are forks available. For example:

Mine: https://crates.io/crates/winresource
The one by tauri: https://crates.io/crates/tauri-winres

I will see to it that the toml version is incremented on my fork.

**Comment by BenjaminRi** [comment]
It is merged in `winresource = "0.1.15"`

**Comment by WindSoilder** [comment]
Hi @BenjaminRi , thanks for your information.

I'll try to use winresource..

**Pull request closed without merging**
